Started logging messages at Fri Apr 14 16:16:27 2023
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 1 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 30
Info:            Created 
Info:        Working on 31
Info:            Created 
Info:        Working on 37
Info:            Created 
Info:        Working on 47
Info:            Created 
Info:        Working on 54
Info:            Created 
Info:        Working on 55
Info:            Created 
Info:        Working on 51
Info:            Created 
Info:        Working on 42
Info:            Created 
Info:        Working on 7
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1e-06
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Fri Apr 14 16:16:27 2023
